GtecIt/Controllers/CursoItemController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web.Mvc;
using AutoMapper;
using System.Collections.Generic;
using System.Data;
using System.IO;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using GtecIt.Util;
using GtecIt.ViewModels;
using GtecIt.Domain.Entities;
using GtecIt.Infra.Data.Core;
using GtecIt.Models;
using Microsoft.Ajax.Utilities;

using GtecIt.Util;


namespace GtecIt.Controllers
{
    public class CursoItemController : Controller
    {
        private readonly IUnitOfWork _uoW;

        public CursoItemController(IUnitOfWork uoW)
        {
            _uoW = uoW;

        }


        public ActionResult Index(OrcamentoItemIndexViewModel model, string tipoacao)
        {
            if (tipoacao != null)
                model.ConsultaTodos = true;

            if (VerificarFiltroVazio(model))
            {
                if (!model.ConsultaTodos)
                    return View(model);

                model.Grid = Mapper.Map<List<OrcamentoItemGridViewModel>>(_uoW.OrcamentoItens.ObterTodos().ToList().OrderBy(x => x.id_stqitorcamento));
                model.ConsultaTodos = true;
                return View(model);
            }

            model.ConsultaTodos = false;

            model.Grid = Mapper.Map<List<OrcamentoItemGridViewModel>>(_uoW.OrcamentoItens.ObterTodos().Where(x => x.id_stqitorcamento.Equals(model.id_stqitorcamento)).ToList().OrderBy(x => x.id_stqitorcamento));
            return View(model);

        }

        public ActionResult Create(string codigo, string codigo2)
        {
            var model = new OrcamentoItemCreateViewModel();

            model.id_stqporcamento = Convert.ToInt16(codigo);

            model.DropdownProduto = _uoW.Produtos.ObterTodos()
                 .OrderBy(x => x.desc_produto)
                 .Select(x => new SelectListItem { Text = x.desc_produto, Value = x.Id_stqcdprd.ToString() })
                 .ToList();
            model.id_grlconvenio = Convert.ToInt32(codigo2);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OrcamentoItemCreateViewModel model)
        {
            if (model.desconto == null)
            {
                model.desconto = 0;
            }
            if (model.descontoperc == null)
            {
                model.descontoperc = 0;
            }
            ModelState.Clear();

            if (!TryValidateModel(model))
            {
                var validationErrors = string.Join(",",
                    ModelState.Values.Where(E => E.Errors.Count > 0)
                    .SelectMany(E => E.Errors)
                    .Select(E => E.ErrorMessage)
                    .ToArray());

                return View(model);
            }
            model.status = "0";
            _uoW.OrcamentoItens.Salvar(Mapper.Map<OrcamentoItem>(model));
            _uoW.Complete();
            return Json(true);
        }



        public ActionResult Edit(int codigo)
        {
            var model = Mapper.Map<OrcamentoItemEditViewModel>(_uoW.OrcamentoItens.ObterPorId(codigo));
            //model.id_stqporcamento = Convert.ToInt16(codigo);

            model.DropdownProduto = _uoW.Produtos.ObterTodos()
                 .OrderBy(x => x.desc_produto)
                 .Select(x => new SelectListItem { Text = x.desc_produto, Value = x.Id_stqcdprd.ToString() })
                 .ToList();
            if (model == null)
                return HttpNotFound();

            return View(model);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(OrcamentoItemEditViewModel model)
        {

            if (model.Vl_unitario != null)
            {
                Decimal aux_vl = Convert.ToDecimal(model.Vl_unitario);


            }
            if (model.desconto == null)
            {
                model.desconto = 0;
            }
            if (model.descontoperc == null)
            {
                model.descontoperc = 0;
            }
            ModelState.Clear();

            if (!TryValidateModel(model))
            {
                var validationErrors = string.Join(",",
                    ModelState.Values.Where(E => E.Errors.Count > 0)
                    .SelectMany(E => E.Errors)
                    .Select(E => E.ErrorMessage)
                    .ToArray());

                return View(model);
            }
            model.status = "0";
            _uoW.OrcamentoItens.Atualizar(Mapper.Map<OrcamentoItem>(model));
            _uoW.Complete();

            return Json(true);
        }


        [HttpPost]
        public JsonResult Delete(int codigo)
        {
            var model = _uoW.OrcamentoItens.ObterPorId(codigo);

            if (model == null)
            {

                return Json(false);
            }
            try
            {

                //_orcamentoItemApp.Remove(model);
                _uoW.OrcamentoItens.RemoverPorId(codigo);
                _uoW.Complete();
            }
            catch (Exception)
            {

                throw;
            }


            return Json(true);
        }

        public bool VerificarFiltroVazio(OrcamentoItemIndexViewModel model)
        {
            model = model ?? new OrcamentoItemIndexViewModel();

            var ehVazio = model.id_stqitorcamento.Equals(0);

            return ehVazio;
        }
    }

}

GtecIt/Controllers/PrecoController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web.Mvc;
using AutoMapper;
using System.Collections.Generic;
using System.IO;
using GtecIt.Util;
using GtecIt.ViewModels;
using GtecIt.Domain.Entities;
using GtecIt.Infra.Data.Core;
using Microsoft.Ajax.Utilities;

namespace GtecIt.Controllers
{
    public class PrecoController : Controller
    {
        private readonly IUnitOfWork _uoW;

        public PrecoController(IUnitOfWork uoW)
        {
            _uoW = uoW;

        }

        public ActionResult Index(PrecoIndexViewModel model, string tipoacao)
        {
            if (tipoacao != null)
                model.ConsultaTodos = true;

            if (VerificarFiltroVazio(model))
            {
                if (!model.ConsultaTodos)
                    return View(model);

                model.Grid = Mapper.Map<List<PrecoGridViewModel>>(_uoW.Precos.ObterTodos().ToList().OrderBy(x => x.produtos.desc_produto));
                model.ConsultaTodos = true;
                return View(model);
            }

            model.ConsultaTodos = false;

            model.Grid = Mapper.Map<List<PrecoGridViewModel>>(_uoW.Precos.ObterTodos().Where(x => x.produtos.desc_produto.Contains(model.produtos.desc_produto)).ToList().OrderBy(x => x.produtos.desc_produto));
            return View(model);

        }

        public ActionResult Create(string codigo)
        {
            var model = new PrecoCreateViewModel();

            model.DropdownConvenio = _uoW.Convenios.ObterTodos()
                   .OrderBy(x => x.grlbasic.nome)
                   .Select(x => new SelectListItem { Text = x.grlbasic.nome, Value = x.id_grlconvenio.ToString() })
                   .ToList();

            model.id_stqcdprd = Convert.ToInt32(codigo);
            /*model.DropdownIdentifica = _tipotelefoneApp.GetAll()
                    .OrderBy(x => x.descricao)
                    .Select(x => new SelectListItem { Text = x.descricao, Value = x.id_grlidtel.ToString()})
                    .ToList();

            model.DropdownSexo = _sexoApp.GetAll()
                    .OrderBy(x => x.descricao)
                    .Select(x => new SelectListItem { Text = x.descricao, Value = x.Id_gercdsexo.ToString() })
                    .ToList();
            //preencher lista
           // model.EstadoCivil = Mapper.Map<List<EstadoCivilEditViewModel>>(_estadoCivilApp.GetAll().ToList());*/
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PrecoCreateViewModel model)
        {
            /*model.ddd_telefone = FiltroDeCaracteres.RemoverCaracteresEspeciais(model.ddd_telefone);
            model.ddd_telefone2 = FiltroDeCaracteres.RemoverCaracteresEspeciais(model.ddd_telefone2);
           
            
            checa_relacionamento(model);
            */
            ModelState.Clear();

            if (!TryValidateModel(model))
            {
                var validationErrors = string.Join(",",
                    ModelState.Values.Where(E => E.Errors.Count > 0)
                    .SelectMany(E => E.Errors)
                    .Select(E => E.ErrorMessage)
                    .ToArray());

                return View(model);
            }

            _uoW.Precos.Salvar(Mapper.Map<Preco>(model));
            _uoW.Complete();
            return Json(true);
            // return RedirectToAction("Edit", new { codigo =_precoApp.GetAll().LastOrDefault().Id_stqcdprd});
        }



        public ActionResult Edit(int codigo)
        {
            var model = Mapper.Map<PrecoEditViewModel>(_uoW.Precos.ObterPorId(codigo));


            model.DropdownConvenio = _uoW.Convenios.ObterTodos()
                  .OrderBy(x => x.grlbasic.nome)
                  .Select(x => new SelectListItem { Text = x.grlbasic.nome, Value = x.id_grlconvenio.ToString() })
                  .ToList();


            /*if (model.Id_stqcdgrp.HasValue)
                model.nome_grupo = _grupoApp.GetById(model.Id_stqcdgrp.Value).desc_grupo;

            if (model.Id_stqsbgrp.HasValue)
                model.nome_subgrupo = _subgrupoApp.GetById(model.Id_stqsbgrp.Value).desc_subgrupo;
            /*if (model == null)
                return HttpNotFound();

            if (model.Id_grlprofi.HasValue)
                model.NomeProfissao = _profissaoApp.GetById(model.Id_grlprofi.Value).descricao;

            model.DropdownEstado = _estadoCivilApp.GetAll()
                   .OrderBy(x => x.descricao)
                   .Select(x => new SelectListItem { Text = x.descricao, Value = x.Id_grlcivil.ToString() })
                   .ToList();

            model.DropdownIdentifica = _tipotelefoneApp.GetAll()
                    .OrderBy(x => x.descricao)
                    .Select(x => new SelectListItem { Text = x.descricao, Value = x.id_grlidtel.ToString() })
                    .ToList();

            model.DropdownSexo = _sexoApp.GetAll()
                    .OrderBy(x => x.descricao)
                    .Select(x => new SelectListItem { Text = x.descricao, Value = x.Id_gercdsexo.ToString() })
                    .ToList();

            */

            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PrecoEditViewModel model)
        {
            /*model.ddd_telefone = FiltroDeCaracteres.RemoverCaracteresEspeciais(model.ddd_telefone);
            model.ddd_telefone2 = FiltroDeCaracteres.RemoverCaracteresEspeciais(model.ddd_telefone2);
            
            checa_relacionamento_edicao(model);*/

            ModelState.Clear();

            if (!TryValidateModel(model))
            {
                var validationErrors = string.Join(",",
                    ModelState.Values.Where(E => E.Errors.Count > 0)
                    .SelectMany(E => E.Errors)
                    .Select(E => E.ErrorMessage)
                    .ToArray());

                return View(model);
            }

            _uoW.Precos.Atualizar(Mapper.Map<Preco>(model));
            _uoW.Complete();

            return Json(true);

        }


        [HttpPost]
        public JsonResult Delete(int codigo)
        {
            var model = _uoW.Precos.ObterPorId(codigo);

            if (model == null)
            {
                return Json(false);
            }

            _uoW.Precos.RemoverPorId(codigo);
            _uoW.Complete();

            return Json(true);
        }

        public bool VerificarFiltroVazio(PrecoIndexViewModel model)
        {
            model = model ?? new PrecoIndexViewModel();

            var ehVazio = model.produtos.desc_produto.IsNullOrWhiteSpace();

            return ehVazio;
        }
        public JsonResult ObteValor(int codigo, int codigo2)
        {
            var fornecedor = _uoW.Precos.ObterTodos().OrderByDescending(x => x.vigencia).FirstOrDefault(x => x.produtos.Id_stqcdprd == codigo && x.id_grlconvenio == codigo2);

            return fornecedor == null ? Json(false, JsonRequestBehavior.AllowGet) : Json(fornecedor.preco, JsonRequestBehavior.AllowGet);
        }


    }
}

GtecIt/Views/CursoItem/Create.cshtml
@model GtecIt.ViewModels.OrcamentoItemCreateViewModel

@{
    Layout = null;
}

<form id="formInclusao" class="form-horizontal" role="form">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Incluir - Itens Orçamento</h4>
    </div>
    <div class="modal-body">

        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => Model.id_stqporcamento)
        @Html.HiddenFor(x => x.id_stqporcamento)
        <div class="form-group">
            <div class="col-sm-6">
                <label>Procedimento</label>
                @Html.DropDownListFor(x => x.id_stqcdprd, Model.DropdownProduto, "Selecione...", new { @class = "form-control", @name = "NomeProduto", @id = "NomeProduto" })
            </div>

            <div class="col-md-2">
                <label>Quantidade</label>
                <input id="qtd" name="qtd" type="text" class="form-control" maxlength="50">
            </div>
            <div class="col-md-4">
                <label>Vl. Unit.</label>
                @Html.TextBoxFor(model => model.Vl_unitario, new { @class = "form-control dinheiro" ,@readonly= true })
            </div>

        </div>
        <div class="form-group">
            <div class="col-sm-4">
                <label>Desconto</label>
                
                @Html.TextBoxFor(model => model.desconto, new { @class = "form-control dinheiro"})
            </div>
            <div class="col-sm-4">
                <label>Desconto %</label>
                <input id="descontoperc" name="descontoperc" type="text" class="form-control" maxlength="50">
            </div>

            <div class="col-sm-4">
                <label>Vl.Total</label>
                @Html.TextBoxFor(model => model.Valor_total, new { @class = "form-control dinheiro" })
            </div>

        </div>

    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-ok"></span> Confirmar</button>
        &nbsp;&nbsp;
        <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancelar</button>
    </div>
</form>

@Scripts.Render("~/bundles/mask")
@Scripts.Render("~/Scripts/gtec/modal.Produto.js")
<script type="text/javascript">


    $('.dinheiro').maskMoney({
        decimal: ",",
        thousands: ".",
        allowZero: true,
        defaultZero: true
    });

    
    $('#NomeProduto').change(function () {

        
        var codigo = $('#NomeProduto').val();
        var codigo2 = @Model.id_grlconvenio;
        
        
        $.ajax({
            type: 'GET',
            url: '@Url.Action("ObteValor","Preco")',
            data: { "codigo": codigo, "codigo2" : codigo2 },
            success: function(data) {
                if (!data) {
                    $("#Vl_unitario").maskMoney('mask',0);
                    $(this).focus();
                } else {
                    console.log(data);
                    $("#Vl_unitario").maskMoney('mask',data);
                    $('#qtd').focus();
                }
            },
            error: function(xhr, status, error) {
                alert(error);
            }
        });


        //};
    });
    $('#formInclusao').on('submit', function (e) {
        var vl_unit = $('#Vl_unitario').val();
        if (vl_unit.length > 0) 
        {
            vl_unit = vl_unit.replace(",", ".");
            vl_unit = parseFloat(vl_unit);
        }
        if (vl_unit <= 0) {
            alert("Favor informar o valor unitário");
            return false;
        }
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Create", "CursoItem")',
            data: $("#formInclusao").serialize(),
            success: function (result) {
                if (result == true) {
                    location.reload();
                    $("modalInclusao").modal('hide');
                } else {
                    alert("Ocorreu um erro.");
                }
            },
            error: function (xhr, status, error) {
                alert(error);
            }
        });
    });

    function calcula_valor_total() {

        
        var vl_total = 0;
        var qtd = 0;
        var vl_unit = 0;
        var vl_desconto = 0;
        var vl_perc = 0;

        qtd = $('#qtd').val();

        if (qtd.length > 0) 
        {
            qtd = parseFloat(qtd);
        }

        vl_unit = $('#Vl_unitario').val();
        if (vl_unit.length > 0) 
        {
            vl_unit = vl_unit.replace(",", ".");
            vl_unit = parseFloat(vl_unit);
        }

        vl_desconto = $('#desconto').val();
        if (vl_desconto.length > 0) 
        {
            vl_desconto = vl_desconto.replace(",", ".");
            vl_desconto = parseFloat(vl_desconto);
        }

        vl_perc = $('#descontoperc').val();
        if (vl_desconto.length > 0) 
        {
            vl_perc = vl_perc.replace(",", ".");
            vl_perc = parseFloat(vl_perc);
        }


        vl_total = (qtd * vl_unit) - vl_desconto;
        vl_total = vl_total - (vl_total * (vl_perc / 100));
        vl_total = parseFloat(vl_total);

        //console.log(vl_total);

        $("#Valor_total").maskMoney('mask',vl_total);
    }

    $('#qtd').blur(function (e) {
        calcula_valor_total();
    });

    $('#Vl_unitario').blur(function (e) {
        calcula_valor_total();
    });

    $('#desconto').blur(function (e) {
        calcula_valor_total();
    });

    $('#descontoperc').blur(function (e) {
        calcula_valor_total();
    });



</script>

GtecIt/Views/CursoItem/Edit.cshtml
@model GtecIt.ViewModels.OrcamentoItemEditViewModel

@{
    Layout = null;
}
<form id="formEdicao" class="form-horizontal" role="form">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Editar - Itens Orçamento</h4>
    </div>
    <div class="modal-body">

        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => Model.id_stqporcamento)
        @Html.HiddenFor(x => Model.id_stqitorcamento)
        <div class="form-group">
            <div class="col-sm-6">
                <label>Procedimento</label>
                @Html.DropDownListFor(x => x.id_stqcdprd, Model.DropdownProduto, "Selecione...", new { @class = "form-control", @name = "NomeProduto", @id = "NomeProduto" })

            </div>

            <div class="col-md-2">
                <label>Quantidade</label>
                @Html.TextBoxFor(model => model.qtd, new { @class = "form-control", @name = "qtd", @id = "qtd" })
            </div>
            <div class="col-md-4">
                <label>Vl. Unit.</label>

                @Html.TextBoxFor(model => model.Vl_unitario, new { @class = "form-control ", @name = "vl_unitario", @id = "vl_unitario" })
            </div>

        </div>
        <div class="form-group">
            <div class="col-sm-4">
                <label>Desconto</label>

                @Html.TextBoxFor(model => model.desconto, new { @class = "form-control ", @name = "desconto", @id = "desconto" })
            </div>
            <div class="col-sm-4">
                <label>Desconto %</label>

                @Html.TextBoxFor(model => model.descontoperc, new { @class = "form-control ", @name = "descontoperc", @id = "descontoperc" })
            </div>

            <div class="col-sm-4">
                <label>Vl.Total</label>
                @Html.TextBoxFor(model => model.Valor_total, new { @class = "form-control dinheiro", @name = "vl_total", @id = "vl_total" })
            </div>

        </div>

    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-ok"></span> Confirmar</button>
        &nbsp;&nbsp;
        <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancelar</button>
    </div>
</form>

<script src="~/Scripts/defaults.js"></script>
@Scripts.Render("~/Scripts/gtec/modal.Produto.js")
<script type="text/javascript">

    $(document).ready(function () {
        calcula_valor_total();
    });

   
    
    $('#formEdicao').on('submit', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Edit", "CursoItem")',
            data: $("#formEdicao").serialize(),
            success: function (result) {
                if (result == true) {
                    location.reload();
                    $("#modalEdicao").modal('hide');
                } else {
                    alert("Esse registro foi atualizado ou excluído em outro local. Por favor, recarregue a página");
                }
            },
            error: function (xhr, status, error) {
                alert(error);
            }
        });
    });
    function calcula_valor_total() {

        var  vl_total = 0.00;
        var  qtd = 0;
        var   vl_unit = 0.00;
        var  vl_desconto = 0.00;
        var    vl_perc = 0.00;


        qtd = (document.getElementById('qtd'));

        if (qtd.value == '') {

            qtd = 0;
        } else
        {
            qtd = (document.getElementById('qtd').value.replace(",","."));


        }

        vl_unit = (document.getElementById('vl_unitario'));
        if (vl_unit.value == '')
        {

            vl_unit = 0;
        }
        else
        {
            vl_unit = (document.getElementById('vl_unitario').value.replace(".", "").replace(".", "."));
            vl_unit = parseFloat(vl_unit);

        }

        vl_desconto = (document.getElementById('desconto'));
        if (vl_desconto.value == '')
        {

            vl_desconto = 0;
        }
        else
        {
            vl_desconto = (document.getElementById('desconto').value.replace(",", "."));
        }

        vl_perc = (document.getElementById('descontoperc'));
        if (vl_perc.value == '') {

            vl_perc = 0;
        }
        else {
            vl_perc = (document.getElementById('descontoperc').value.replace(",", "."));
        }

        vl_total = (qtd * vl_unit) - vl_desconto;
        vl_total = vl_total - (vl_total * (vl_perc / 100));
        
        $("#vl_total").val(vl_total);
        
        
    }

    
    $('#qtd').blur(function(e) {
        calcula_valor_total();
    });

    $('#vl_unitario').blur(function (e) {
        calcula_valor_total();
    });
    $('#desconto').blur(function (e) {
        calcula_valor_total();
    });
    $('#descontoperc').blur(function (e) {
        calcula_valor_total();
    });

</script>

GtecIt/Views/CursoItem/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>