GtecIt/ViewModels/Endereco/EnderecoCreateViewModel.cs
namespace GtecIt.ViewModels
{
    public class EnderecoCreateViewModel 
    {
        public int Id_Grendbasico { get; set; }
        public int? Id_grlbasic { get; set; }
        public string Logradouro { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string Cep { get; set; }
        public int? Id_grlidtel { get; set; }

        private int? _Id_grlcdusu = 1;

        public int? Id_grlcdusu
        {
            get { return _Id_grlcdusu; }
            set { _Id_grlcdusu = value; }
        }

    }
}

GtecIt/ViewModels/Endereco/EnderecoEditViewModel.cs
namespace GtecIt.ViewModels
{
    public class EnderecoEditViewModel 
    {
        public int Id_Grendbasico { get; set; }
        public int? Id_grlbasic { get; set; }
        public string Logradouro { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string Cep { get; set; }
        public int? Id_grlidtel { get; set; }
        public int? Id_grlcdusu { get; set; }

    }
}

GtecIt/ViewModels/Endereco/EnderecoGridViewModel.cs
namespace GtecIt.ViewModels
{
    public class EnderecoGridViewModel 
    {

        public int Id_Grendbasico { get; set; }
        public int? Id_grlbasic { get; set; }
        public string Logradouro { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string Cep { get; set; }
        public int? Id_grlidtel { get; set; }
        public int? Id_grlcdusu { get; set; }
       }
}

GtecIt/ViewModels/Endereco/EnderecoIndexViewModel.cs
using System.Collections.Generic;


namespace GtecIt.ViewModels
{
    public class EnderecoIndexViewModel 
    {
        public EnderecoIndexViewModel()
        {
            Grid = new List<EnderecoGridViewModel>();
        }

        public bool ConsultaTodos { get; set; }
        public int Id_Grendbasico { get; set; }
        public int? Id_grlbasic { get; set; }
        public string Logradouro { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string Cep { get; set; }
        public int? Id_grlidtel { get; set; }
        public int? Id_grlcdusu { get; set; }
        public List<EnderecoGridViewModel> Grid { get; set; }

    }
}

GtecIt/Controllers/EnderecoController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web.Mvc;
using AutoMapper;
using System.Collections.Generic;
using System.IO;
using GtecIt.Util;
using GtecIt.ViewModels;
using GtecIt.Domain.Entities;
using GtecIt.Infra.Data.Core;
using Microsoft.Ajax.Utilities;

namespace GtecIt.Controllers
{
    public class EnderecoController : Controller
    {
        private readonly IUnitOfWork _uoW;

        public EnderecoController(IUnitOfWork uoW)
        {
            _uoW = uoW;

        }

        public ActionResult Index(EnderecoIndexViewModel model, string tipoacao)
        {
            if (tipoacao != null)
                model.ConsultaTodos = true;

            if (VerificarFiltroVazio(model))
            {
                if (!model.ConsultaTodos)
                    return View(model);

                model.Grid = Mapper.Map<List<EnderecoGridViewModel>>(_uoW.Enderecos.ObterTodos().ToList().OrderBy(x => x.Cep));
                model.ConsultaTodos = true;
                return View(model);
            }

            model.ConsultaTodos = false;

            model.Grid = Mapper.Map<List<EnderecoGridViewModel>>(_uoW.Enderecos.ObterTodos().Where(x => x.Cep.Contains(model.Cep)).ToList().OrderBy(x => x.Cep));
            return View(model);

        }

        public ActionResult Create(string codigo)
        {
            var model = new EnderecoCreateViewModel();
            model.Id_grlbasic = Convert.ToInt16(codigo);
            //model.Id_grlcdusu = 1;
            //model.Id_grlidtel = 1;
            //model.Id_grlbasic = Convert.ToInt32(codigo);

            //model.DropdownIdentifica = _tipotelefoneApp.GetAll()
            //        .OrderBy(x => x.descricao)
            //        .Select(x => new SelectListItem { Text = x.descricao, Value = x.id_grlidtel.ToString()})
            //        .ToList();


            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EnderecoCreateViewModel model)
        {
            ModelState.Clear();

            if (!TryValidateModel(model))
            {
                var validationErrors = string.Join(",",
                    ModelState.Values.Where(E => E.Errors.Count > 0)
                    .SelectMany(E => E.Errors)
                    .Select(E => E.ErrorMessage)
                    .ToArray());

                return View(model);
            }

           _uoW.Enderecos.Salvar(Mapper.Map<Endereco>(model));
            _uoW.Complete();

            return Json(true);
        }



        public ActionResult Edit(int codigo)
        {
            var model = Mapper.Map<EnderecoEditViewModel>(_uoW.Enderecos.ObterPorId(codigo));

            if (model == null)
                return HttpNotFound();

            return View(model);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EnderecoEditViewModel model)
        {

            ModelState.Clear();

            if (!TryValidateModel(model))
            {
                var validationErrors = string.Join(",",
                    ModelState.Values.Where(E => E.Errors.Count > 0)
                    .SelectMany(E => E.Errors)
                    .Select(E => E.ErrorMessage)
                    .ToArray());

                return View(model);
            }

            _uoW.Enderecos.Atualizar(Mapper.Map<Endereco>(model));
            _uoW.Complete();

            return Json(true);
        }


        [HttpPost]
        public JsonResult Delete(int codigo)
        {
            var model = _uoW.Enderecos.ObterPorId(codigo);

            if (model == null)
            {
                return Json(false);
            }

            _uoW.Enderecos.RemoverPorId(codigo);
            _uoW.Complete();

            return Json(true);
        }

        public bool VerificarFiltroVazio(EnderecoIndexViewModel model)
        {
            model = model ?? new EnderecoIndexViewModel();

            var ehVazio = model.Logradouro.IsNullOrWhiteSpace();

            return ehVazio;
        }
    }
}

GtecIt/Views/Endereco/Create.cshtml
@model GtecIt.ViewModels.EnderecoCreateViewModel
<script src="~/Scripts/defaults.js"></script>
@{
    Layout = null;
}
<form id="formInclusao" class="form-horizontal" role="form">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Incluir - Endereços</h4>
    </div>
    <div class="modal-body">

        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => Model.Id_grlbasic)
        @Html.HiddenFor(x => x.Id_Grendbasico)
        <div class="form-group">
            <div class="col-sm-2">
                <label>Cep</label>
                
                <input id="cep" name="Cep" type="text" class="form-control" maxlength="50" required autofocus>
            </div>
            <div class="col-sm-6">
                <label>Logradouro</label>
                
                <input id="logradouro" name="logradouro" type="text" class="form-control" maxlength="50" >
            </div>

            <div class="col-md-4">
                <label>Complemento</label>
                <input id="complemento" name="complemento" type="text" class="form-control" maxlength="50" >
            </div>

        </div>
        <div class="form-group">
            <div class="col-sm-4">
                <label>Bairro</label>
                <input id="bairro" name="bairro" type="text" class="form-control" maxlength="50" >
            </div>
            <div class="col-sm-4">
                <label>Cidade</label>
                <input id="cidade" name="cidade" type="text" class="form-control" maxlength="50" >
            </div>

            <div class="col-sm-4">
                <label>Estado</label>
                <input id="estado" name="estado" type="text" class="form-control" maxlength="50" >
            </div>

        </div>

    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-ok"></span> Confirmar</button>
        &nbsp;&nbsp;
        <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancelar</button>
    </div>
</form>

<script type="text/javascript">
    $('#formInclusao').on('submit', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Create", "Endereco")',
            data: $("#formInclusao").serialize(),
            success: function (result) {
                if (result == true) {
                    location.reload();
                    $("modalInclusao").modal('hide');
                } else {
                    alert("Ocorreu um erro.");
                }
            },
            error: function (xhr, status, error) {
                alert(error);
            }
        });
    });

    $("#cep").blur(function() {

        //Nova variável "cep" somente com dígitos.
        var cep = $(this).val().replace(/\D/g, '');

        //Verifica se campo cep possui valor informado.
        if (cep != "") {

            //Expressão regular para validar o CEP.
            var validacep = /^[0-9]{8}$/;

            //Valida o formato do CEP.
            if(validacep.test(cep)) {

                //Preenche os campos com "..." enquanto consulta webservice.
                $("#logradouro").val("...");
                $("#bairro").val("...");
                $("#cidade").val("...");
                $("#estado").val("...");
                

                //Consulta o webservice viacep.com.br/
                $.getJSON("//viacep.com.br/ws/"+ cep +"/json/?callback=?", function(dados) {

                    if (!("erro" in dados)) {
                        //Atualiza os campos com os valores da consulta.
                        $("#logradouro").val(dados.logradouro);
                        $("#bairro").val(dados.bairro);
                        $("#cidade").val(dados.localidade);
                        $("#estado").val(dados.uf);
                        
                    } //end if.
                    else {
                        //CEP pesquisado não foi encontrado.
                        limpa_formulário_cep();
                        alert("CEP não encontrado.");
                    }
                });
            } //end if.
            else {
                //cep é inválido.
                limpa_formulário_cep();
                alert("Formato de CEP inválido.");
            }
        } //end if.
        else {
            //cep sem valor, limpa formulário.
            limpa_formulário_cep();
        }
    });
    
    function limpa_formulário_cep() {
        // Limpa valores do formulário de cep.
        $("#logradouro").val("");
        $("#bairro").val("");
        $("#cidade").val("");
        $("#estado").val("");
        
    }
</script>

GtecIt/Views/Endereco/Edit.cshtml
@model GtecIt.ViewModels.EnderecoEditViewModel
<script src="~/Scripts/defaults.js"></script>
@{
    Layout = null;
}
<form id="formEdicao" class="form-horizontal" role="form">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Editar - Endereços</h4>
    </div>
    <div class="modal-body">

        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => x.Id_grlbasic)
        @Html.HiddenFor(x => x.Id_Grendbasico)
        <div class="form-group">
            <div class="col-sm-2">
                <label>Código</label>
                @Html.TextBoxFor(model => model.Cep, new { @class = "form-control" })
            </div>
            <div class="col-sm-6">
                <label>Logradouro</label>
                @Html.TextBoxFor(model => model.Logradouro, new { @class = "form-control" })
            </div>
            
            <div class="col-md-4">
                <label>Complemento</label>
                @Html.TextBoxFor(model => model.Complemento, new { @class = "form-control" })
            </div>

        </div>
        <div class="form-group">
            <div class="col-sm-4">
                <label>Bairro</label>
                @Html.TextBoxFor(model => model.Bairro, new { @class = "form-control" })
            </div>
            <div class="col-sm-4">
                <label>Cidade</label>
                @Html.TextBoxFor(model => model.Cidade, new { @class = "form-control" })
            </div>

            <div class="col-sm-4">
                <label>Estado</label>
                @Html.TextBoxFor(model => model.Estado, new { @class = "form-control" })
            </div>

        </div>
        
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-ok"></span> Confirmar</button>
        &nbsp;&nbsp;
        <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancelar</button>
    </div>
</form>

<script type="text/javascript">
    $('#formEdicao').on('submit', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Edit", "Endereco")',
            data: $("#formEdicao").serialize(),
            success: function (result) {
                if (result == true) {
                    location.reload();
                    $("#modalEdicao").modal('hide');
                } else {
                    alert("Esse registro foi atualizado ou excluído em outro local. Por favor, recarregue a página");
                }
            },
            error: function (xhr, status, error) {
                alert(error);
            }
        });
    });

</script>

GtecIt/Views/Endereco/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>