GtecIt/Controllers/ProfissaoController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web.Mvc;
using AutoMapper;
using System.Collections.Generic;
using System.IO;
using GtecIt.Util;
using GtecIt.ViewModels;
using GtecIt.Domain.Entities;
using GtecIt.Infra.Data.Core;
using Microsoft.Ajax.Utilities;

namespace GtecIt.Controllers
{
    public class ProfissaoController : Controller
    {
        private readonly IUnitOfWork _uoW;

        public ProfissaoController(IUnitOfWork uoW)
        {
            _uoW = uoW;

        }

        public ActionResult Index(ProfissaoIndexViewModel model, string tipoacao)
        {
            if (tipoacao != null)
                model.ConsultaTodos = true;

            if (VerificarFiltroVazio(model))
            {
                if (!model.ConsultaTodos)
                    return View(model);

                model.Grid = Mapper.Map<List<ProfissaoGridViewModel>>(_uoW.Profissoes.ObterTodos().ToList());
                model.ConsultaTodos = true;
                return View(model);
            }

            model.ConsultaTodos = false;

            model.Grid = Mapper.Map<List<ProfissaoGridViewModel>>(_uoW.Profissoes.ObterTodos().Where(x => x.descricao.Contains(model.descricao)).ToList());
            return View(model);

        }

        public ActionResult Create()
        {
            return View();
        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Create(ProfissaoCreateViewModel model)
        {
            if (!ModelState.IsValid)
                return Json(false);

            _uoW.Profissoes.Salvar(Mapper.Map<Profissao>(model));
            _uoW.Complete();
            return Json(true);
        }

        public ActionResult Edit(int codigo)
        {
            var model = Mapper.Map<ProfissaoEditViewModel>(_uoW.Profissoes.ObterPorId(codigo));

            if (model == null)
                return HttpNotFound();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Edit(ProfissaoEditViewModel model)
        {
            if (!ModelState.IsValid)
                return Json(false);

            _uoW.Profissoes.Salvar(Mapper.Map<Profissao>(model));
            _uoW.Complete();
            return Json(true);
        }

        [HttpPost]
        public JsonResult Delete(int codigo)
        {
            var model = _uoW.Profissoes.ObterPorId(codigo);

            if (model == null)
            {
                return Json(false);
            }

            _uoW.Profissoes.RemoverPorId(codigo);
            _uoW.Complete();
            return Json(true);
        }

        public bool VerificarFiltroVazio(ProfissaoIndexViewModel model)
        {
            model = model ?? new ProfissaoIndexViewModel();

            var ehVazio = model.descricao.IsNullOrWhiteSpace();

            return ehVazio;
        }

        public JsonResult ObterDescricaoProfissao(int codigo)
        {
            var fornecedor = _uoW.Profissoes.ObterTodos().FirstOrDefault(x => x.Id_grlprofi == codigo);

            return fornecedor == null ? Json(false, JsonRequestBehavior.AllowGet) : Json(fornecedor.descricao, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ObterProfissao(string tipoConsulta, string filtro)
        {
            string html = "";
            //// tipoConsulta = codigo || descricao

            switch (tipoConsulta)
            {
                case "codigo":
                    {
                        var codigo = Convert.ToInt32(filtro);
                        var model = _uoW.Profissoes.ObterTodos().Where(x => x.Id_grlprofi == codigo);

                        foreach (var item in model)
                        {
                            html += "<tr>";
                            html += string.Format("<td class=\"col-sm-2 text-center\">{0}</td>", item.Id_grlprofi);
                            html += string.Format("<td class=\"col-sm-9\">{0}</td>", item.descricao);
                            html +=
                                string.Format(
                                    "<td class=\"col-sm-1\"><a href=\"javascript:btnConfirmarModalProfisao({0}, '{1}');\"  class=\"btn-confirmar\"><span class=\"glyphicon glyphicon-ok\"></span></a></td>",
                                    item.Id_grlprofi, item.descricao);
                            html += "</tr>";
                        }
                    }
                    break;
                case "descricao":
                    {
                        var model =
                            _uoW.Profissoes.ObterTodos()
                                .Where(x => x.descricao.ToLower().Trim().Contains(filtro.ToLower().Trim()));

                        foreach (var item in model)
                        {
                            html += "<tr>";
                            html += string.Format("<td class=\"col-sm-2 text-center\">{0}</td>", item.Id_grlprofi);
                            html += string.Format("<td class=\"col-sm-9\">{0}</td>", item.descricao);
                            html +=
                                string.Format(
                                    "<td class=\"col-sm-1\"><a href=\"javascript:btnConfirmarModalProfissao({0}, '{1}');\" class=\"btn-confirmar\"><span class=\"glyphicon glyphicon-ok\"></span></a></td>",
                                    item.Id_grlprofi, item.descricao);
                            html += "</tr>";
                        }
                    }
                    break;
                case "todos":
                    {
                        var model = _uoW.Profissoes.ObterTodos();

                        foreach (var item in model)
                        {
                            html += "<tr>";
                            html += string.Format("<td class=\"col-sm-2 text-center\">{0}</td>", item.Id_grlprofi);
                            html += string.Format("<td class=\"col-sm-9\">{0}</td>", item.descricao);
                            html +=
                                string.Format(
                                    "<td class=\"col-sm-1\"><a href=\"javascript:btnConfirmarModalProfissao({0}, '{1}');\" class=\"btn-confirmar\"><span class=\"glyphicon glyphicon-ok\"></span></a></td>",
                                    item.Id_grlprofi, item.descricao);
                            html += "</tr>";
                        }
                    }
                    break;
            }

            return Json(html);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult CreateModal(ProfissaoCreateViewModel model)
        {
            if (!ModelState.IsValid)
                return Json(false);
            try
            {
                _uoW.Profissoes.Salvar(Mapper.Map<Profissao>(model));
                _uoW.Complete();

                var TipoTelefone = _uoW.Profissoes.ObterTodos().OrderByDescending(x => x.Id_grlprofi).FirstOrDefault();
                return Json(TipoTelefone);
            }
            catch(Exception ex)
            {

            }
            return Json(false);
        }

    }
}

GtecIt/Views/Profissao/Create.cshtml
@model GtecIt.ViewModels.ProfissaoEditViewModel

@{
    Layout = null;
}
<form id="formInclusao" class="form-horizontal" role="form">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Incluir - Profissão</h4>
    </div>
    <div class="modal-body">

        @Html.AntiForgeryToken()
        <div class="row">
            <div class="form-group">
                <label for="Descricao" class="col-md-2 control-label">Descrição</label>
                <div class="col-md-5">
                    <input id="Descricao" name="Descricao" type="text"
                           class="form-control" maxlength="50" required autofocus>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" id="btnModalIncluirConfirmar" class="btn btn-primary">
            <span class="glyphicon glyphicon-ok"></span> Confirmar
        </button>
        &nbsp;&nbsp;
        <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancelar</button>
    </div>
</form>

<script type="text/javascript">

    $('#formInclusao').on('submit', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Create", "Profissao")',
            data: $("#formInclusao").serialize(),
            success: function (result) {
                if (result == true) {
                    location.reload();
                    $("modalInclusao").modal('hide');
                } else {
                    alert("Ocorreu um erro.");
                }
            },
            error: function (xhr, status, error) {
                alert(error);
            }
        });
    });

    

</script>

GtecIt/Views/Profissao/Edit.cshtml
@model GtecIt.ViewModels.ProfissaoEditViewModel

@{
    Layout = null;
}
<form id="formEdicao" class="form-horizontal" role="form">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Editar - Sexo</h4>
    </div>
    <div class="modal-body">
        @Html.AntiForgeryToken()
        <div class="row">
            @Html.HiddenFor(x => x.Id_grlprofi)
            <div class="form-group">
                @Html.LabelFor(x => x.descricao, new { @class = "col-md-2 control-label" })
                <div class="col-md-5">
                    @Html.TextBoxFor(x => x.descricao, new { @class = "form-control", @autofocus = "autofocus", required = "required", maxlength = "50" })
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit"  class="btn btn-primary"><span class="glyphicon glyphicon-ok"></span> Confirmar</button>
        &nbsp;&nbsp;
        <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancelar</button>
    </div>
</form>

<script type="text/javascript">

    $('#formEdicao').on('submit', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Edit", "Profissao")',
            data: $("#formEdicao").serialize(),
            success: function (result) {
                if (result == true) {
                    location.reload();
                    $("modalEdicao").modal('hide');
                } else {
                    alert("Esse registro foi atualizado ou excluído em outro local. Por favor, recarregue a página");
                }
            },
            error: function (xhr, status, error) {
                alert(error);
            }
        });
    });
   
</script>

GtecIt/Views/Profissao/Index.cshtml
@model GtecIt.ViewModels.ProfissaoIndexViewModel

@{
    ViewBag.Title = "Profissao";
}


@using (Html.BeginForm("Index", "Profissao", FormMethod.Get, new { @class = "form-inline", @role = "form" }))
{

    <fieldset>
        <legend>@ViewBag.Title</legend>
        <div class="form-group">
            @Html.LabelFor(model => model.descricao, new { @class = "control-label" })
            @Html.TextBoxFor(x => x.descricao, new { @class = "form-control", @placeholder = "Profissao", @autofocus = "autofocus" })
        </div>
        <button name="tipoacao" type="submit" value="consultatodos" class="btn btn-primary">
            <i class="glyphicon glyphicon-search"></i> Consultar
        </button>

        <a id="btnNovo" href="#" class="btn btn-primary">
            <span class="glyphicon glyphicon-plus"></span> Novo
        </a>
    </fieldset>
}
@if (Model != null && Model.Grid.Any())
{
    <div id="grid">
        <hr />
        <table id="tabelaGrid" class="table table-bordered table-striped table-hover table-responsive dt-responsive">
            <thead>
                <tr>
                    <th>Profissão</th>
                    <th class="text-center"></th>
                    <th class="text-center"></th>
                </tr>
            </thead>
            <tbody id="corpoTabelaGrid">
                @foreach (var item in Model.Grid)
                {
                    <tr class="@item.Id_grlprofi">
                        <td>@item.descricao</td>
                        <td class="text-center col-sm-1">
                            <a href="#" class="glyphicon glyphicon-pencil btnGridEditar" data-id="@item.Id_grlprofi"></a>
                        </td>
                        <td class="text-center col-sm-1">
                            <a href="#" class="glyphicon glyphicon-trash btnGridExcluir" data-toggle="modal" data-target="#modalExclusao" data-id="@item.Id_grlprofi"></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}

<div id="modalExclusao" class="modal fade" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Exclusão de registro</h4>
            </div>
            <div class="modal-body">
                <p class="text-center">Deseja realmente excluir este registro? </p>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-primary " id="btnModalExclusaoConfirmar">
                    <span class="glyphicon glyphicon-ok"></span> Confirma
                </a>
                &nbsp;&nbsp;
                <button type="button" class="btn btn-default" data-dismiss="modal" id="btnModalExclusaoCancelar">
                    <span class="glyphicon glyphicon-remove"></span> Cancelar
                </button>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">

        $(document).ready(function () {
            $('#tabelaGrid').DataTable();
        });

        $('#btnNovo').click(function (e) {
            e.preventDefault();
            var url = '@Url.Action("Create", "Profissao")';

            var modal, modalDialog, modalContent;
            modal = $('<div id="modalInclusao" class="modal fade" "/>');
            modalDialog = $('<div class="modal-dialog" />');
            modalContent = $('<div class="modal-content" />');

            modal.modal('hide')
                .append(modalDialog)
                .on('hidden.bs.modal', function () { $(this).remove(); })
                .appendTo('body');


            modalDialog.append(modalContent);

            $.get(url, function (data) {
                modalContent.html(data);
                modal.on('show.bs.modal', function () { $(this).find('input:first').focus(); });
                modal.modal('show');
            });
        });

        $('.btnGridEditar').click(function (e) {
            e.preventDefault();
            var url = '@Url.Action("Edit", "Profissao")' + '?codigo=' + $(this).data('id');

            var modal, modalDialog, modalContent;
            modal = $('<div id="modalEdicao" class="modal fade" "/>');
            modalDialog = $('<div class="modal-dialog" />');
            modalContent = $('<div class="modal-content" />');

            modal.modal('hide')
             .append(modalDialog)
             .on('hidden.bs.modal', function () { $(this).remove(); })
             .appendTo('body');

            modalDialog.append(modalContent);

            $.get(url, function (data) {
                modalContent.html(data);
                modal.modal('show');
            });
        });



        $(".btnGridExcluir").click(function (e) {
            e.preventDefault();
            var id = $(this).data('id');
            var linha = $("." + id);
            $("#btnModalExclusaoConfirmar").off("click").click(function (e) {
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("Delete", "Profissao")',
                    data: {
                        "codigo": id
                    },
                    success: function (data) {
                        if (data == true) {
                            linha.remove();
                            $('#modalExclusao').modal('hide');
                            if ($("#corpoTabelaGrid").children("tr").length > 0) {
                                return true;
                            }
                            else {
                                $("#grid").remove();
                                return true;
                            }
                        } else {
                            alert("Ocorreu um erro ao tentar excluir o registro.");
                            $("#btnModalExclusaoCancelar").click();
                        }
                    },
                    error: function (xhr, status, error) {
                        alert(error);
                    }
                });
            });
        });

       


        

    </script>
}