GtecIt/Controllers/AulaLogController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web.Mvc;
using AutoMapper;
using System.Collections.Generic;
using System.Data;
using System.IO;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using GtecIt.Util;
using GtecIt.ViewModels;
using GtecIt.Domain.Entities;
using GtecIt.Infra.Data.Core;
using GtecIt.Models;
using Microsoft.Ajax.Utilities;

using GtecIt.Util;


namespace GtecIt.Controllers
{
    public class AulaLogController : Controller
    {
        private readonly IUnitOfWork _uoW;

        public AulaLogController(IUnitOfWork uoW)
        {
            _uoW = uoW;

        }


        public ActionResult Index(AulaLogIndexViewModel model, string tipoacao)
        {
            if (tipoacao != null)
                model.ConsultaTodos = true;
            else
            {

                model.inicio = DateTime.Now;
                model.Fim = DateTime.Now;
            }

            if (VerificarFiltroVazio(model))
            {
                if (!model.ConsultaTodos)
                    return View(model);

               /* model.Grid = Mapper.Map<List<AulaLogGridViewModel>>(_uoW.AulasLog.ObterTodos().ToList());
                model.ConsultaTodos = true;
                return View(model);*/
            }

            model.ConsultaTodos = false;

            //model.Grid = Mapper.Map<List<AulaLogGridViewModel>>(_uoW.AulasLog.ObterTodos().Where(x => x.idGercdAulasLog.Equals(model.idGercdAulasLog)).ToList().OrderBy(x => x.idGercdAulasLog));
            var teste = _uoW.AulasLog.ObterAulas(model.idGercdAulasLog, model.inicio, model.Fim,Convert.ToInt32( model.id_Stqcporcamento_inicio)).ToList();

            model.Grid = Mapper.Map<List<AulaLogGridViewModel>>( _uoW.AulasLog.ObterAulas(model.idGercdAulasLog, model.inicio, model.Fim,Convert.ToInt32(model.id_Stqcporcamento_inicio)).ToList());
            model.ConsultaTodos = true;
            //migrar aulas 

            return View(model);

        }

      


      


        
        private string convertePortugues(string dia)
        {
            var dia_portugues = "";
            if (dia == "Monday")
            {
                dia_portugues = "Segunda";
            }
            if (dia == "Tuesday")
            {
                dia_portugues = "Terça";
            }
            if (dia == "Wednesday")
            {
                dia_portugues = "Quarta";
            }
            if (dia == "Thursday")
            {
                dia_portugues = "Quinta";
            }
            if (dia == "Friday")
            {
                dia_portugues = "Sexta";
            }
            if (dia == "Saturday")
            {
                dia_portugues = "Sábado";

            }
            return dia_portugues;
        }

        public ActionResult ObterQtd(string codigo, string codigo2)
        {
            var model = new AulaCreateViewModel();
            var orcamento = _uoW.Orcamentos.ObterPorId(Convert.ToInt32(codigo));

            model.Inicio_contrato = Convert.ToDateTime(orcamento.Dt_orcamento);
            model.id_Stqcporcamento = orcamento.id_Stqcporcamento;
            int? codigo_prd = 0;
            foreach (var item in orcamento.itemorcamentos)
            {
                codigo_prd = item.id_stqcdprd;
            }
            var plano = _uoW.PrecosPlano.ObterTodos().Where(x => x.id_stqcdprd == codigo_prd).FirstOrDefault();
            if (plano != null)
            {
                model.qtd_aulas = plano.qtd_aulas;

                model.Vencimento_contrato = model.Inicio_contrato.AddDays(plano.qtd_dias_plano);
            }
            var resposta = new
            {

                Sucesso = true,
                quantidade = model.qtd_aulas
            };
            return Json(resposta, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Edit(int codigo)
        {
            var model = Mapper.Map<AulaLogEditViewModel>(_uoW.AulasLog.ObterPorId(codigo));
            //model.id_stqporcamento = Convert.ToInt16(codigo);

            /* model.DropdownProduto = _uoW.Produtos.ObterTodos()
                  .OrderBy(x => x.desc_produto)
                  .Select(x => new SelectListItem { Text = x.desc_produto, Value = x.Id_stqcdprd.ToString() })
                  .ToList();
             if (model == null)
                 return HttpNotFound();
                 */
            return View(model);

        }
       
        public bool VerificarFiltroVazio(AulaLogIndexViewModel model)
        {
            model = model ?? new AulaLogIndexViewModel();

            var ehVazio = model.idGercdAulasLog.Equals(0);

            return ehVazio;
        }


        
    }

}

GtecIt/Controllers/BancoController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web.Mvc;
using AutoMapper;
using System.Collections.Generic;
using System.IO;
using GtecIt.Util;
using GtecIt.ViewModels;
using GtecIt.Domain.Entities;
using GtecIt.Infra.Data.Core;
using Microsoft.Ajax.Utilities;

namespace GtecIt.Controllers
{
    public class BancoController : Controller
    {
        private readonly IUnitOfWork _uoW;

        public BancoController(IUnitOfWork uoW)
        {
            _uoW = uoW;

        }

        public ActionResult Index(BancoIndexViewModel model, string tipoacao)
        {
            if (tipoacao != null)
                model.ConsultaTodos = true;

            if (VerificarFiltroVazio(model))
            {
                if (!model.ConsultaTodos)
                    return View(model);

                model.Grid = Mapper.Map<List<BancoGridViewModel>>(_uoW.Bancos.ObterTodos());
                model.ConsultaTodos = true;
                return View(model);
            }

            model.ConsultaTodos = false;

            model.Grid =
                Mapper.Map<List<BancoGridViewModel>>(
                    _uoW.Bancos.ObterTodos().Where(x => x.desc_banco.Contains(model.desc_banco)).ToList());
            return View(model);

        }

        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Create(BancoCreateViewModel model)
        {
            if (!ModelState.IsValid)
                return Json(false);

            try
            {
                _uoW.Bancos.Salvar(Mapper.Map<Banco>(model));
                _uoW.Complete();
            }
            catch (Exception ex)
            {

            }
            // _bancoApp.Add(Mapper.Map<Banco>(model));

            return Json(true);
        }

        public ActionResult Edit(int codigo)
        {
            //var model = Mapper.Map<BancoEditViewModel>(_bancoApp.GetById(codigo));
            var model =
                Mapper.Map<BancoEditViewModel>(_uoW.Bancos.ObterTodos().FirstOrDefault(x => x.id_Fincdbanco == codigo));
            if (model == null)
                return HttpNotFound();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Edit(BancoEditViewModel model)
        {
            if (!ModelState.IsValid)
                return Json(false);

            _uoW.Bancos.Atualizar(Mapper.Map<Banco>(model));
            _uoW.Complete();
            // _bancoApp.Update(Mapper.Map<Banco>(model));

            return Json(true);
        }

        [HttpPost]
        public JsonResult Delete(int codigo)
        {
            var model = _uoW.Bancos.ObterPorId(codigo); //_bancoApp.GetById(codigo);

            if (model == null)
            {
                return Json(false);
            }

            _uoW.Bancos.RemoverPorId(codigo);
            _uoW.Complete();
            //_bancoApp.Remove(model);

            return Json(true);
        }

        public bool VerificarFiltroVazio(BancoIndexViewModel model)
        {
            model = model ?? new BancoIndexViewModel();

            var ehVazio = model.desc_banco.IsNullOrWhiteSpace();

            return ehVazio;
        }
    }
}

GtecIt/Controllers/GrupoController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web.Mvc;
using AutoMapper;
using System.Collections.Generic;
using System.IO;
using GtecIt.Util;
using GtecIt.ViewModels;
using GtecIt.Domain.Entities;
using GtecIt.Infra.Data.Core;
using Microsoft.Ajax.Utilities;

namespace GtecIt.Controllers
{
    public class GrupoController : Controller
    {
        private readonly IUnitOfWork _uoW;

        public GrupoController(IUnitOfWork uoW)
        {
            _uoW = uoW;

        }

        public ActionResult Index(GrupoIndexViewModel model, string tipoacao)
        {
            if (tipoacao != null)
                model.ConsultaTodos = true;

            if (VerificarFiltroVazio(model))
            {
                if (!model.ConsultaTodos)
                    return View(model);

                model.Grid = Mapper.Map<List<GrupoGridViewModel>>(_uoW.Grupos.ObterTodos().ToList());
                model.ConsultaTodos = true;
                return View(model);
            }

            model.ConsultaTodos = false;

            model.Grid = Mapper.Map<List<GrupoGridViewModel>>(_uoW.Grupos.ObterTodos().Where(x => x.desc_grupo.Contains(model.desc_grupo)).ToList());
            return View(model);

        }

        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Create(GrupoCreateViewModel model)
        {
            if (!ModelState.IsValid)
                return Json(false);

           _uoW.Grupos.Salvar(Mapper.Map<Grupo>(model));
            _uoW.Complete();
            return Json(true);
        }

        public ActionResult Edit(int codigo)
        {
            var model = Mapper.Map<GrupoEditViewModel>(_uoW.Grupos.ObterPorId(codigo));

            if (model == null)
                return HttpNotFound();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Edit(GrupoEditViewModel model)
        {
            if (!ModelState.IsValid)
                return Json(false);

            _uoW.Grupos.Atualizar(Mapper.Map<Grupo>(model));
            _uoW.Complete();
            return Json(true);
        }

        [HttpPost]
        public JsonResult Delete(int codigo)
        {
            var model =_uoW.Grupos.ObterPorId(codigo);

            if (model == null)
            {
                return Json(false);
            }

            _uoW.Grupos.RemoverPorId(codigo);

            return Json(true);
        }

        public bool VerificarFiltroVazio(GrupoIndexViewModel model)
        {
            model = model ?? new GrupoIndexViewModel();

            var ehVazio = model.desc_grupo.IsNullOrWhiteSpace();

            return ehVazio;
        }
        public JsonResult ObterDescricaoGrupo(int codigo)
        {
            var fornecedor = _uoW.Grupos.ObterTodos().FirstOrDefault(x => x.Id_stqcdgrp == codigo);


            return fornecedor == null ? Json(false, JsonRequestBehavior.AllowGet) : Json(fornecedor.desc_grupo, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ObterGrupo(string tipoConsulta, string filtro)
        {
            string html = "";
            //// tipoConsulta = codigo || descricao

            switch (tipoConsulta)
            {
                case "codigo":
                    {
                        var codigo = Convert.ToInt32(filtro);
                        var model = _uoW.Grupos.ObterTodos().Where(x => x.Id_stqcdgrp == codigo);

                        foreach (var item in model)
                        {
                            html += "<tr>";
                            html += string.Format("<td class=\"col-sm-2 text-center\">{0}</td>", item.Id_stqcdgrp);
                            html += string.Format("<td class=\"col-sm-9\">{0}</td>", item.desc_grupo);
                            html +=
                                string.Format(
                                    "<td class=\"col-sm-1\"><a href=\"javascript:btnConfirmarModalGrupo({0}, '{1}');\"  class=\"btn-confirmar\"><span class=\"glyphicon glyphicon-ok\"></span></a></td>",
                                    item.Id_stqcdgrp, item.desc_grupo);
                            html += "</tr>";
                        }
                    }
                    break;
                case "descricao":
                    {
                        var model =
                           _uoW.Grupos.ObterTodos()
                                .Where(x => x.desc_grupo.ToLower().Trim().Contains(filtro.ToLower().Trim()));

                        foreach (var item in model)
                        {
                            html += "<tr>";
                            html += string.Format("<td class=\"col-sm-2 text-center\">{0}</td>", item.Id_stqcdgrp);
                            html += string.Format("<td class=\"col-sm-9\">{0}</td>", item.desc_grupo);
                            html +=
                                string.Format(
                                    "<td class=\"col-sm-1\"><a href=\"javascript:btnConfirmarModalGrupo({0}, '{1}');\" class=\"btn-confirmar\"><span class=\"glyphicon glyphicon-ok\"></span></a></td>",
                                    item.Id_stqcdgrp, item.desc_grupo);
                            html += "</tr>";
                        }
                    }
                    break;
                case "todos":
                    {
                        var model = _uoW.Grupos.ObterTodos();

                        foreach (var item in model)
                        {
                            html += "<tr>";
                            html += string.Format("<td class=\"col-sm-2 text-center\">{0}</td>", item.Id_stqcdgrp);
                            html += string.Format("<td class=\"col-sm-9\">{0}</td>", item.desc_grupo);
                            html +=
                                string.Format(
                                    "<td class=\"col-sm-1\"><a href=\"javascript:btnConfirmarModalGrupo({0}, '{1}');\" class=\"btn-confirmar\"><span class=\"glyphicon glyphicon-ok\"></span></a></td>",
                                    item.Id_stqcdgrp, item.desc_grupo);
                            html += "</tr>";
                        }
                    }
                    break;
            }

            return Json(html);
        }

        public JsonResult CreateModal(GrupoCreateViewModel model)
        {
            if (!ModelState.IsValid)
                return Json(false);

            _uoW.Grupos.Salvar(Mapper.Map<Grupo>(model));

            var TipoTelefone = _uoW.Grupos.ObterTodos().OrderByDescending(x => x.Id_stqcdgrp).FirstOrDefault();

            return Json(TipoTelefone);
        }

        public JsonResult AutoCompleteGrupoPreFetch()
        {
            try
            {
                var resultado = _uoW.Grupos.ObterTodos().Select(x =>
                new
                {
                    Id = x.Id_stqcdgrp.ToString(),
                    Codigo = x.Id_stqcdgrp.ToString(),
                    Descricao = x.desc_grupo.ToString(),
                }).ToList();

                return Json(new { success = true, results = resultado }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {

                throw;
            }

        }
    }
}

GtecIt/Views/Shared/_Layout.cshtml
@using GtecIt.Util
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Gtec", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Cadastro Básico
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Pessoas", "Index", "Pessoa")</li>
                            <li>@Html.ActionLink("Alunos", "Index", "Cliente")</li>
                            <li>@Html.ActionLink("Professor", "Index", "Dentista")</li>

                            <li>@Html.ActionLink("Usuario", "Index2", "Login")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Sexo", "Index", "Sexo")</li>
                            <li>@Html.ActionLink("Profissão", "Index", "Profissao")</li>
                            <li>@Html.ActionLink("Estado Civil", "Index", "EstadoCivil")</li>
                            <li>@Html.ActionLink("Tipo de Telefone", "Index", "TipoTelefone")</li>
                            <li>@Html.ActionLink("Centro de Custo", "Index", "CentrodeCusto")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Tipos de Pagamento", "Index", "TipoPagamento")</li>
                            <li>@Html.ActionLink("Tipos de Titulos", "Index", "TipoTitulo")</li>
                            <li>@Html.ActionLink("Bancos", "Index", "Banco")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Planos", "Index", "Plano")</li>
                            <li>@Html.ActionLink("Grupos de Serviços", "Index", "Grupo")</li>
                            <li>@Html.ActionLink("Subgrupos de Serviços", "Index", "SubGrupo")</li>
                            <li>@Html.ActionLink("Serviços", "Index", "Produto")</li>

                            <li>@Html.ActionLink("Agenda", "Index", "Events")</li>
                            <li>@Html.ActionLink("Ranking", "Index", "Ranking")</li>
                            <li>@Html.ActionLink("Ranking Feminino", "Index", "RankingFeminino")</li>
                            <li>@Html.ActionLink("Ranking Dupla", "Index", "RankingDupla")</li>


                        </ul>
                    </li>
                    <li class="dropdown">
                        @if (GerenciaSession.UsarioLogado.Administrador == "S")
                        {
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Contratos
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">


                                <li>@Html.ActionLink("Contrato - Aulas", "Index", "Orcamento")</li>
                                <li>@Html.ActionLink("Renovação de Contrato - Aulas", "Renovacao", "Orcamento")</li>
                                <li>@Html.ActionLink("Ativação de Contratos", "Ativacao", "Orcamento")</li>
                                <li>@Html.ActionLink("Liberação de Horários", "Liberacao", "Orcamento")</li>
                                <li>@Html.ActionLink("Modificações de Horarios", "Index", "AulaLog")</li>
                                <li>@Html.ActionLink("Notas de Entrada", "Index", "NotaEntrada")</li>

                            </ul>
                        }
                    </li>
                    <li class="dropdown">
                        @if (GerenciaSession.UsarioLogado.Administrador == "S")
                        {
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Financeiro
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">

                                <li>@Html.ActionLink("Quitação de Titulos a Receber", "Index", "NotaEntrada")</li>
                                <li>@Html.ActionLink("Quitação de Titulos a Pagar", "Index", "Pedido")</li>
                            </ul>
                        }
                        </li>
                    <li class="dropdown">
                        @if (GerenciaSession.UsarioLogado.Administrador == "S")
                        {
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Relatorios
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">

                                <li>@Html.ActionLink("Contratos por periodo", "RelAtendimentoPeriodo", "Relatorio")</li>
                                <li>@Html.ActionLink("Contratos por periodo Sintético", "RelAtendimentoPeriodoporconnvenio", "Relatorio")</li>
                                <li>@Html.ActionLink("Contratos cancelados por periodo ", "RelAtendimentoPeriodocancelado", "Relatorio")</li>
                                <li>@Html.ActionLink("Contratos sem titulos a receber por periodo ", "RelAtendimentoPeriodosemtitulos", "Relatorio")</li>
                                <li>@Html.ActionLink("Contratos por Professor", "Relatendimentopordentista", "Relatorio")</li>
                                <li>@Html.ActionLink("Contratos por Professor - Sintético", "Relatendimentopordentistasintetico", "Relatorio")</li>
                                <li>@Html.ActionLink("Serviços por Professor", "RelExamespordentista", "Relatorio")</li>
                                <li>@Html.ActionLink("Aulas por Professor", "RelAulasporprofessor", "Relatorio")</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Titulos a receber", "RelTitulosareceber", "Relatorio")</li>
                            </ul>
                        }
                        </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a>v1.5</a></li>
                    <li class="dropdown">
                        @{
                            var usuario = GerenciaSession.UsarioLogado != null ? GerenciaSession.UsarioLogado.Login : "";
                        }
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp; @usuario <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">

                            <li>@Html.ActionLink("Sair", "Logout", "Login")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - GTec</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/typeahead")
    @Scripts.Render("~/bundles/jqueryajax")
    @*@Scripts.Render("~/bundles/jqueryval")*@
    @Scripts.Render("~/bundles/datatables")
    @Scripts.Render("~/bundles/datetimepicker")
    @Scripts.Render("~/bundles/mask")
    @Scripts.Render("~/bundles/default")


    @RenderSection("scripts", required: false)


</body>
</html>